spring:
  cloud:
    stream:
      instanceIndex: 1
      instanceCount: 2
      kafka:
        bindings:
          reply:
            consumer:
              autoRebalanceEnabled: false
      bindings:
        input:
          destination: requests
          group: requestsGroup
          consumer:
            partitioned: true
        output:
          destination: responses
          producer:
            partition-count: 2
            partition-key-expression: headers['partitionKey']
        reply:
          destination: responses
          group: responseGroup
          consumer:
            partitioned: true
        request:
          destination: requests
          producer:
            partition-count: 2

logging:
  level:
    root: INFO
    org:
      apache:
        kafka: OFF
server:
  port: 0